[tools]
atuin = "latest"
bat = "latest"
carapace = "latest"
ccache = "latest"
chezmoi = "latest"
cmake = "latest"
croc = "latest"
delta = "latest"
difftastic = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
hyperfine = "latest"
jujutsu = "latest"
lazygit = "latest"
neovim = "latest"
ninja = "latest"
node = "latest"
opencode = "latest"
ripgrep = "latest"
rust = "latest"
starship = "latest"
tmux = "latest"
uv = "latest"
yazi = "latest"
zellij = "latest"
zoxide = "latest"
